version: "3"

services:
  laravel-backend:
    container_name: laravel-backend
    build:
      context: ./laravel-backend
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - my-network
    restart: on-failure

  react-frontend:
    container_name: react-frontend
    build:
      context: ./react-frontend
    volumes:
      - ./react-frontend/src:/usr/src/app/src
    ports:
      - 3000:80
    networks:
      - my-network

  db:
    container_name: db-mysql
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: innoscripta
      MYSQL_DATABASE: innoscripta
      MYSQL_USER: innoscripta
      MYSQL_PASSWORD: innoscripta
    networks:
      - my-network

networks:
  my-network:
